### ISSUE TITLE
Y Scrollbar leads to page 'jumping' while switching between menus

### ISSUE THREAD

**Issue by trichner** [BombersBar/website#11]
1. Land on home https://bb-drunkenirishman.herokuapp.com/
2. Go to O'Bombercare https://bb-drunkenirishman.herokuapp.com/obombercare

Expected: Top Bar (Navigation) stays in place
Actual: Everything moves a bit because the home page is long enough to show a Y-Scrollbar, which is very annoying.

An `overflow-y: scroll` CSS rule should do the trick.

**Comment by BrandonMurnane** [comment]
i cant seem to recreate but i pushed that css on that page if you wanna check ina while if its fixed thanks alot for the catch :)

**Comment by trichner** [comment]
If you add the issue numer in the commit message I'd see the corresponding commit.

e.g.: #11 :)

**Comment by BrandonMurnane** [comment]
ah cool ill try that in the future :P

**Comment by trichner** [comment]
I think you added it to the wrong element, should be on 'body' ;)

```
body {
   overflow-y: scroll;
}
```

**Comment by trichner** [comment]
Works! Great!
